name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  GITHUB_TOKEN: ${{ github.token }}
  RUST_BACKTRACE: 1

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: space-wizards/submodule-dependency@v0.1.5
    - uses: snickerbockers/submodules-init@v4
    - name: Build
      run: bash run install
    - name: Run
      run: bash run tests/test.txt
    - name: Tests
      run: bash run test 
